### ISSUE TITLE
Rebuild with nodejs

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [PCL-Community/HookWFB#1]
@chichundan

**Comment by shankkyy** [comment]
hey Hii, @JingHai-Lingyun can you please tell me more about the issue 
I want to work on this nodejs issue

**Comment by MoYuan-CN** [comment]
> hey Hii, @JingHai-Lingyun can you please tell me more about the issue 
> I want to work on this nodejs issue
> 

i dont have time on this
please contact @Deep-Dark-Forest to get more information about this issue

and also you can contact @WForst-Breeze to ask about join our community

**Comment by Deep-Dark-Forest** [comment]
@shankkyy Hello,Thank you for your attention to this issue!The function of this repository is to store a robot code based on WebHook. At present, its functions include: automatically adding a "√ 完成＂ label when a PR is merged, automatically adding a "× 拒绝" label when a PR is closed, automatically adding a "⇵ 通过" label when a PR is approved by a user named WForst-Breeze, and automatically requesting the review of WForst-Breeze when a PR is created. At present, we have implemented these functions using Python, but we found that it has many bugs. It doesn't work at all!We want to use nodejs to rebuild it. If you like, you can fork our repository and launch a pull request. Thanks a lot!

**Comment by wuliaodexiaoluo** [comment]
好像改错了

**Comment by MoYuan-CN** [comment]
i will check later
